// export const CREATE_FLASHCARD = "CREATE_FLASHCARD";
// export const RETRIEVE_FLASHCARDS = "RETRIEVE_FLASHCARDS";
// export const UPDATE_FLASHCARD = "UPDATE_FLASHCARD";
// export const DELETE_FLASHCARD = "DELETE_FLASHCARD";
// export const DELETE_ALL_FLASHCARDS = "DELETE_ALL_FLASHCARDS";